### ISSUE TITLE
Wrong returning value

### ISSUE THREAD

**Issue by peti2001** [go-micro/plugins#20]
The `injectTraceIntoCtx` function is supposed to inject the trace into the context. But instead of that it just returns with the same context.
https://github.com/go-micro/plugins/blob/1d6f7b8f9464faf5ece160503ce3478c87e0af85/v2/wrapper/trace/opencensus/opencensus.go#L28-L32

The `metadata.Set` function returns with the new context not modifying the parameter
https://github.com/asim/go-micro/blob/master/metadata/metadata.go#L54-L65

I think this is how it is supposed to be:
```go
ctx = metadata.Set(ctx, TracePropagationField, base64.RawStdEncoding.EncodeToString(spanCtx))
```

With this change, the trace is sent between the microservices and I can see them in Jaeger:
<img width="1242" alt="Screen Shot 2022-05-26 at 2 20 48 PM" src="https://user-images.githubusercontent.com/2922738/170486635-e952bb59-aa3a-4967-ba20-aeaae574e29c.png">

Without the change:
<img width="1244" alt="Screen Shot 2022-05-26 at 2 21 05 PM" src="https://user-images.githubusercontent.com/2922738/170486683-a7fb4fe0-3ba3-4b24-9c5b-2bcbd69c2b29.png">

**Comment by Davincible** [comment]
Fixed

**Comment by peti2001** [comment]
Thanks
