### ISSUE TITLE
a problem by client at version of v2

### ISSUE THREAD

**Issue by xuyunjin1998** [go-micro/plugins#26]
There are some problems here by v2 plugin of http client at git address "https://github.com/go-micro/plugins/tree/main/v2/client/http"

by reading origin code , i find the a http request call for other micro service , why does request method designed as 'POST'  and was forced.

the other http client at JAVA Stack such as 'feign'、'rest template' , I can use http method in GET\POST\PUT ..........

**Comment by Davincible** [comment]
Could you provide some code examples to showcase the problems?

**Comment by xuyunjin1998** [comment]
`
func (h *httpClient) call(ctx context.Context, node *registry.Node, req client.Request, rsp interface{}, opts client.CallOptions) error {
	// set the address
	address := node.Address
	header := make(http.Header)
	if md, ok := metadata.FromContext(ctx); ok {
		for k, v := range md {
			header.Set(k, v)
		}
	}

	// set timeout in nanoseconds
	header.Set("Timeout", fmt.Sprintf("%d", opts.RequestTimeout))
	// set the content type for the request
	header.Set("Content-Type", req.ContentType())

	// get codec
	cf, err := h.newHTTPCodec(req.ContentType())
	if err != nil {
		return errors.InternalServerError("go.micro.client", err.Error())
	}

	// marshal request
	b, err := cf.Marshal(req.Body())
	if err != nil {
		return errors.InternalServerError("go.micro.client", err.Error())
	}

	buf := &buffer{bytes.NewBuffer(b)}
	defer buf.Close()

	hreq := &http.Request{
		Method: "POST",
		URL: &url.URL{
			Scheme: "http",
			Host:   address,
			Path:   req.Endpoint(),
		},
		Header:        header,
		Body:          buf,
		ContentLength: int64(len(b)),
		Host:          address,
	}

	// make the request
	hrsp, err := http.DefaultClient.Do(hreq.WithContext(ctx))
	if err != nil {
		return errors.InternalServerError("go.micro.client", err.Error())
	}
	defer hrsp.Body.Close()

	// parse response
	b, err = ioutil.ReadAll(hrsp.Body)
	if err != nil {
		return errors.InternalServerError("go.micro.client", err.Error())
	}

	// unmarshal
	if err := cf.Unmarshal(b, rsp); err != nil {
		return errors.InternalServerError("go.micro.client", err.Error())
	}

	return nil
}
`
see code for ‘Method: "POST",’ ， it forced  as 'post'


since only the variable "endpoint" can be used to build HTTP requests through the "client interface".

code
`
type Client interface {
	........
	NewRequest(service, endpoint string, req interface{}, reqOpts ...RequestOption) Request
	......
}
`

Why the variable 'endpoint' can't do this as 
`
req := client.NewRequest({microServiceCode}, '{httpMethod} {httpPath}', map[string]string{})
`

such as 
`
req := client.NewRequest({microServiceCode}, 'GET /path', map[string]string{})
`
by the way,
the function  named 'Method' of  the Interface named Request can return 'Get'
and the function  named 'Endpoint' of  the Interface named Request can return '/path'

**Comment by Davincible** [comment]
It's not an http client in the traditional sence like `net/http` is. The client package is a client for the `go-micro` service, which happens to use the HTTP transport to communicate, with the predefined `POST` method. If you want to call it with any other method you would have to use an HTTP client such as `net/http`

**Comment by xuyunjin1998** [comment]
thanks's u
