### ISSUE TITLE
plugins/v4/wrapper/breaker/hystrix/ readMe

### ISSUE THREAD

**Issue by radishChao** [go-micro/plugins#28]
hystrix.NewClientWrapper(hystrix.WithFilter(func(c context.Context, e error) error {
			if e == ErrLetItPass {
				return nil
			}
			return e
	})

should be:
hystrix.NewClientWrapper(hystrix.WithFilter(func(c context.Context, e error) bool{
			if e == ErrLetItPass {
				return true
			}
			return false
	})

**Comment by Davincible** [comment]
Would you like to put this in a PR?

**Comment by radishChao** [comment]
> 
okey

**Comment by radishChao** [comment]
I’ll do it

**Comment by radishChao** [comment]
> Would you like to put this in a PR?

I’ll do it
