### ISSUE TITLE
package "go-micro.dev/v4/cmd" unavailable yet

### ISSUE THREAD

**Issue by drnp** [go-micro/plugins#33]
package "go-micro.dev/v4/cmd" removed from latest version of go-micro

imported in:

v4/cache/redis/redis.go:	"go-micro.dev/v4/cmd"
v4/client/grpc/grpc.go:	"go-micro.dev/v4/cmd"
v4/client/http/http.go:	"go-micro.dev/v4/cmd"
v4/client/mucp/mucp.go:	"go-micro.dev/v4/cmd"
v4/transport/quic/quic.go:	"go-micro.dev/v4/cmd"
v4/transport/utp/utp.go:	"go-micro.dev/v4/cmd"
v4/transport/memory/memory.go:	"go-micro.dev/v4/cmd"
v4/transport/rabbitmq/rabbitmq.go:	"go-micro.dev/v4/cmd"
v4/transport/grpc/grpc.go:	"go-micro.dev/v4/cmd"
v4/transport/tcp/tcp.go:	"go-micro.dev/v4/cmd"
v4/transport/nats/nats.go:	"go-micro.dev/v4/cmd"
v4/server/grpc/grpc.go:	"go-micro.dev/v4/cmd"
v4/server/http/http.go:	"go-micro.dev/v4/cmd"
v4/server/mucp/mucp.go:	"go-micro.dev/v4/cmd"
v4/broker/sqs/sqs.go:	"go-micro.dev/v4/cmd"
v4/broker/snssqs/snssqs.go:	"go-micro.dev/v4/cmd"
v4/broker/memory/memory.go:	"go-micro.dev/v4/cmd"
v4/broker/googlepubsub/googlepubsub.go:	"go-micro.dev/v4/cmd"
v4/broker/rabbitmq/rabbitmq.go:	"go-micro.dev/v4/cmd"
v4/broker/stomp/stomp.go:	"go-micro.dev/v4/cmd"
v4/broker/stan/stan.go:	"go-micro.dev/v4/cmd"
v4/broker/grpc/grpc.go:	"go-micro.dev/v4/cmd"
v4/broker/http/http.go:	"go-micro.dev/v4/cmd"
v4/broker/nsq/nsq.go:	"go-micro.dev/v4/cmd"
v4/broker/proxy/proxy.go:	"go-micro.dev/v4/cmd"
v4/broker/segmentio/segmentio.go:	"go-micro.dev/v4/cmd"
v4/broker/redis/redis.go:	"go-micro.dev/v4/cmd"
v4/broker/kafka/kafka.go:	"go-micro.dev/v4/cmd"
v4/broker/gocloud/gocloud.go:	"go-micro.dev/v4/cmd"
v4/broker/mqtt/mqtt.go:	"go-micro.dev/v4/cmd"
v4/broker/nats/nats.go:	"go-micro.dev/v4/cmd"
v4/auth/jwt/jwt.go:	"go-micro.dev/v4/cmd"
v4/store/cockroach/cockroach.go:	"go-micro.dev/v4/cmd"
v4/store/mysql/mysql.go:	"go-micro.dev/v4/cmd"
v4/store/file/file.go:	"go-micro.dev/v4/cmd"
v4/store/memory/memory.go:	"go-micro.dev/v4/cmd"
v4/store/nats-js/nats.go:	"go-micro.dev/v4/cmd"
v4/store/memcached/memcached.go:	"go-micro.dev/v4/cmd"
v4/store/consul/consul.go:	"go-micro.dev/v4/cmd"
v4/store/redis/redis.go:	"go-micro.dev/v4/cmd"
v4/registry/etcd/etcd.go:	"go-micro.dev/v4/cmd"
v4/registry/mdns/mdns.go:	"go-micro.dev/v4/cmd"
v4/registry/gossip/gossip.go:	"go-micro.dev/v4/cmd"
v4/registry/eureka/eureka.go:	"go-micro.dev/v4/cmd"
v4/registry/proxy/proxy.go:	"go-micro.dev/v4/cmd"
v4/registry/nacos/nacos.go:	"go-micro.dev/v4/cmd"
v4/registry/consul/consul.go:	"go-micro.dev/v4/cmd"
v4/registry/kubernetes/kubernetes.go:	"go-micro.dev/v4/cmd"
v4/registry/zookeeper/zookeeper.go:	"go-micro.dev/v4/cmd"
v4/registry/nats/nats.go:	"go-micro.dev/v4/cmd"
v4/selector/static/static.go:	"go-micro.dev/v4/cmd"
v4/selector/registry/registry.go:	"go-micro.dev/v4/cmd"
v4/selector/label/label.go:	"go-micro.dev/v4/cmd"
v4/config/source/mucp/mucp.go:	"go-micro.dev/v4/cmd"

**Comment by drnp** [comment]
switched to branch "dev"

**Comment by xpunch** [comment]
wip: #32
