### ISSUE TITLE
Cannot import plugins/v4/server/grpc

### ISSUE THREAD

**Issue by wkloucek** [go-micro/plugins#4]
When importing plugins/v4/server/grpc, I get following message:

```
go: finding module for package github.com/go-micro/plugins/v4/client/grpc/v4
go: finding module for package github.com/go-micro/plugins/v4/server/grpc
go: found github.com/go-micro/plugins/v4/server/grpc in github.com/go-micro/plugins/v4/server/grpc v1.0.0
go: downloading github.com/go-micro/plugins/v4/transport/grpc v0.0.0
github.com/owncloud/ocis/ocis-pkg/service/grpc imports
	github.com/go-micro/plugins/v4/server/grpc tested by
	github.com/go-micro/plugins/v4/server/grpc.test imports
	github.com/go-micro/plugins/v4/transport/grpc: reading github.com/go-micro/plugins/v4/transport/grpc/v4/transport/grpc/go.mod at revision v4/transport/grpc/v0.0.0: unknown revision v4/transport/grpc/v0.0.0
```

This is because of these lines:

https://github.com/go-micro/plugins/blob/254c7a4afab66cf0ba0db6dfe8519e468e603107/v4/server/grpc/go.mod#L6-L7

Ideally, they should also point to `v1.0.0` (the most recent version) but I don't know how that fit's in the release process!? Do you plan to always tag all plugins at the same time or will they get separate releases? If the second option is the case, we should be able to fix it once and then get Dependabot / RenovateBot PRs to update the transport plugin automatically after a release.

CC @xpunch

**Comment by xpunch** [comment]
The reason that this can pass the unit tests is it uses replace command to redirect to local modules.
https://github.com/go-micro/plugins/blob/254c7a4afab66cf0ba0db6dfe8519e468e603107/v4/server/grpc/go.mod#L50-L53
I'll fixing the issue you mentioned once I get time.
The reason why I used v0.0.0 was there is no tags when I'm trying to fixing all the errors and failed tests. There is too much plugins, and it takes me a lot of time to rename and fixing failed tests. So I've not tested all the plugins, there may be some plugins still not works fine. I'll fixing all the broken plugins once I know.
I'll also take a look at Dependabot/RenovateBot to help fixing the dependencies issue once I get time.

**Comment by xpunch** [comment]
Hi @wkloucek, do you want to be the maintainer of this repo?
