### ISSUE TITLE
[FEATURE] v4/broker/rabbitmq - parallel message handling

### ISSUE THREAD

**Issue by dbereza-machinify** [go-micro/plugins#40]
**Is your feature request related to a problem? Please describe.**
Enhance v4/broker/rabbitmq plugin to allow for handling incoming broker messages in parallel.

**Describe the solution you'd like**
Currently, it seems the v4/broker/rabbitmq plugin processes messages serially, based on the code below:
https://github.com/go-micro/plugins/blob/0ed40ba1aacebe0d38d871a6272f78125bf68dbc/v4/broker/rabbitmq/rabbitmq.go#L142-L146

This is not ideal for throughput, particularly for messages that take time to process or their handlers end up blocking.

**Additional context**
This could be tied to the `rabbitmq.PrefetchCount` broker option, since that's a limitation of the max number of messages that are retrieved but not acknowledged at a time, but for backwards compatibility another option should probably be provided to enable parallelism.

**Comment by dbereza-machinify** [comment]
Actually, reviewing the code for other broker plugins, it doesn't seem like parallelism is done within a subscriber in general.

Seems like a good option is to instead subscribe multiple times to the same topic with the same handler, opening multiple channels, which requires no changes. 

As such, I think this can be safely closed, sorry for the hassle.

**Comment by Davincible** [comment]
> particularly for messages that take time to process or their handlers end up blocking

I would pass the workload onto another routine, and make the handler only a relay
